name: Notebooks

on: push

jobs:

  build-and-test:
    name: notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
         python-version: 3.7 
         architecture: x64
      - name: Print version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies 
        run: python -m pip install -r requirements.txt
      
      - name: testing-notebooks
        shell: bash -l {0}
        run: |
          cd notebooks && python testNotebooks.py --path notebooks 
